import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  final Map<String, Map<String, String>> _localizedValues;

  AppLocalizations(this.locale, this._localizedValues);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'am', 'om'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    final Map<String, Map<String, String>> localizedValues = {
      'en': {
        // App Title
        'appTitle': 'Harari Prosperity App',

        // Common
        'save': 'Save',
        'cancel': 'Cancel',
        'next': 'Next',
        'back': 'Back',
        'submit': 'Submit',
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',
        'warning': 'Warning',
        'confirm': 'Confirm',
        'delete': 'Delete',
        'edit': 'Edit',
        'search': 'Search',
        'noInternet': 'No internet connection',
        'retry': 'Retry',
        'close': 'Close',

        // Auth
        'login': 'Login',
        'signup': 'Sign Up',
        'email': 'Email',
        'password': 'Password',
        'forgotPassword': 'Forgot Password?',
        'dontHaveAccount': 'Don\'t have an account?',
        'alreadyHaveAccount': 'Already have an account?',
        'loginWithGoogle': 'Continue with Google',
        'loginWithApple': 'Continue with Apple',
        'loginWithFacebook': 'Continue with Facebook',
        'fullName': 'Full Name',
        'phoneNumber': 'Phone Number',
        'confirmPassword': 'Confirm Password',
        'createAccount': 'Create Account',
        'termsAgreement': 'By signing up, you agree to our',
        'termsOfService': 'Terms of Service',
        'privacyPolicy': 'Privacy Policy',
        'and': 'and',
        'welcomeBack': 'Welcome Back!',
        'welcomeMessage': 'Sign in to continue',
        'createNewAccount': 'Create New Account',
        'registerMessage':
            'Fill your information below or register with your social account',

        // Navigation
        'home': 'Home',
        'reports': 'Reports',
        'profile': 'Profile',
        'settings': 'Settings',
        'language': 'Language',
        'logout': 'Logout',
        'selectLanguage': 'Select Language',
        'english': 'English',
        'amharic': 'Amharic',
        'oromo': 'Oromiffa',

        // Reports
        'newReport': 'New Report',
        'reportTitle': 'Report Title',
        'reportDescription': 'Description',
        'reportCategory': 'Category',
        'reportLocation': 'Location',
        'reportDate': 'Date',
        'reportStatus': 'Status',
        'reportImages': 'Images',
        'submitReport': 'Submit Report',
        'reportSubmitted': 'Report Submitted',
        'reportSubmittedMessage': 'Your report has been submitted successfully',
        'viewAllReports': 'View All Reports',
        'myReports': 'My Reports',
        'noReports': 'No reports found',
        'reportDetails': 'Report Details',
        'comments': 'Comments',
        'addComment': 'Add a comment...',
        'post': 'Post',
        'like': 'Like',
        'likes': 'Likes',
        'share': 'Share',
        'report': 'Report',

        // Profile
        'myProfile': 'My Profile',
        'editProfile': 'Edit Profile',
        'changePassword': 'Change Password',
        'accountSettings': 'Account Settings',
        'helpAndSupport': 'Help & Support',
        'aboutApp': 'About App',
        'version': 'Version',
        'logoutConfirmation': 'Are you sure you want to logout?',
        'yes': 'Yes',
        'no': 'No',

        // Settings
        'notifications': 'Notifications',
        'darkMode': 'Dark Mode',
        'privacy': 'Privacy',
        'security': 'Security',
        'termsAndConditions': 'Terms & Conditions',
        'rateApp': 'Rate App',
        'shareApp': 'Share App',
        'clearCache': 'Clear Cache',
        'about': 'About',
        'versionInfo': 'Version Information',
        'deleteAccount': 'Delete Account',
        'faq': 'FAQ',

        // Home Screen
        'hello': 'HELLO',
        'welcomeToHarari':
            'Welcome to Harari Regional Prosperity Party Political Analysis System. This application helps you to share the report to prosperity party office by giving you the guidance of standards to make the report and it gives you choices like document, pictures, links to attach with your report.',
        'toSendReport': 'TO SEND A REPORT',
        'clickHere': 'CLICK HERE',

        // Authentication
        'createAccount': 'Create Account',
        'alreadyHaveAccountLogin': 'Already have an account? Login',
        'forgotPasswordTitle': 'Forgot Password',
        'ifYouWantCreateAccount': 'If You Want To Create Another Account',
        'orSignUpWith': 'or sign up with',
        'dontHaveAccountSignUp': 'Don\'t have an account? Sign Up',
        'or': 'or',

        // Terms and Conditions
        'termsAndConditionsTitle': 'Terms And Conditions',
        'term1': '1. Ea voluptates omnis aut sequi sequi.',
        'term2': '2. Est dolore quce in aliquid ducimus et outem repellendus.',
        'term3': '3. Aut ipsum Quis qui porto quasi aut minus placcati.',
        'term4': '4. Sit consequatur neque do vitae facere.',
        'termBullet1': '- Aut fuga sequi eum voluptatibus provident.',
        'termBullet2':
            '- Eos consequuntur voluptas vel amet eaque aut dignissimos velit.',
        'iAcceptTerms': 'I accept all the terms and conditions',
        'termsDescription':
            'Please read and accept our terms and conditions to continue using the Harari Prosperity App.',
        'termsPoint1':
            '1. You agree to use this application responsibly and in accordance with local laws.',
        'termsPoint2':
            '2. All information provided in reports must be accurate and truthful.',
        'termsPoint3':
            '3. You are responsible for maintaining the confidentiality of your account credentials.',
        'termsPoint4':
            '4. The application may collect and process data as described in our privacy policy.',
        'termsDescription2': 'By using this application, you acknowledge that:',
        'termsBullet1':
            '- You understand the purpose and functionality of the Harari Prosperity Party Political Analysis System.',
        'termsBullet2':
            '- You will use the application for legitimate reporting and analysis purposes only.',
        'termsDescription3':
            'These terms may be updated periodically. Continued use of the application constitutes acceptance of any changes.',
        'readTermsMore':
            'For more detailed information, please visit our website or contact support.',
        'acceptAllTerms': 'I have read and accept all terms and conditions',
        'acceptContinue': 'Accept & Continue',

        // Profile Management
        'changeUsername': 'Change Username',
        'usernameUpdatedSuccessfully': 'Username updated successfully!',
        'passwordSettings': 'Password Settings',
        'passwordChangedSuccessfully': 'Password changed successfully!',

        // Report Screens
        'reportDetail': 'Detail',
        'attachment': 'Attachment',
        'finalStep': 'Final Step',
        'finalStepDescription':
            'You have successfully completed all the required sections of your report. Click finish to submit your report to the Prosperity Party office.',
        'finish': 'Finish',
        'reportCompletedSuccessfully': 'Report completed successfully!',
        'headingTitle': 'Heading title',
        'importanceOfReport': 'Importance of Report',
        'mainPoints': 'Main points',
        'informationSources': 'Information Sources',
        'rolesOfActors': 'Roles of actors and stakeholders',
        'positiveNegativeTrends': 'Positive and Negative trends',
        'takenThemes': 'Taken Themes',
        'implicationsConclusions': 'Implications and Conclusions',
        'scenarios': 'Scenarios',
        'futurePlansActivities': 'Future plans and activities',
        'reportApprovingBody': 'Report approving body',
        'senderName': 'Sender Name',
        'role': 'Role',
        'timeMonthDate': 'Time/Month/Date',
        'file': 'FILE',
        'chooseFile': 'Choose File',
        'link': 'LINK',
        'attachFilesOrLinks': 'Attach Files or Links',
        'selectedFiles': 'Selected Files',
        'pasteLinkHere': 'Paste link here',
        'skip': 'Skip',
        'failedToPickFiles': 'Failed to pick files',
        'noReportIdFound': 'No report ID found',
        'failedToUploadAttachments': 'Failed to upload attachments',

        // Report History
        'view': 'View',
        'createFirstReport': 'Create Your First Report',

        // Report View
        'reportDetails': 'Report Details',
        'completed': 'COMPLETED',
        'basicInformation': 'Basic Information',
        'reportContent': 'Report Content',
        'analysis': 'Analysis',
        'conclusionsFuture': 'Conclusions & Future',
        'reportMetadata': 'Report Metadata',
        'attachments': 'Attachments',
        'fileAttachments': 'File Attachments:',
        'linkAttachment': 'Link Attachment:',
        'reportInformation': 'Report Information',
        'created': 'Created',
        'lastUpdated': 'Last Updated',
        'status': 'Status',
        'reportType': 'Report Type',
        'type': 'Type',
        'receiverName': 'Receiver Name',
        'objectiveOfReport': 'Objective of Report',
        'description': 'Description',
        'untitledReport': 'Untitled Report',

        // Security
        'securityTitle': 'Security',
        'deleteAccountTitle': 'Delete Account',
        'deleteAccountMessage':
            'Are you sure you want to delete your account? This action cannot be undone.',
        'failedToDeleteAccount': 'Failed to delete account',
        'changeUsername': 'Change Username',
        'currentPassword': 'Current Password',
        'newPassword': 'New Password',
        'confirmNewPassword': 'Confirm New Password',
        'passwordRequirements':
            'Password must be at least 8 characters long and include a number',
        'passwordMismatch': 'Passwords do not match',
        'passwordUpdated': 'Password updated successfully',
        'usernameUpdated': 'Username updated successfully',

        // FAQ & Help
        'faqHelp': 'FAQ & Help',
        'faqDescription':
            'This feature helps you submit detailed reports to the Prosperity Party office with all necessary documentation and attachments.',
        'helpCenter': 'Help Center',
        'contactSupport': 'Contact Support',
        'commonQuestions': 'Common Questions',
        'troubleshooting': 'Troubleshooting',
        'userGuide': 'User Guide',
        'videoTutorials': 'Video Tutorials',
        'sendMessage': 'Send Message',
        'yourMessage': 'Your message...',
        'messageSent': 'Your message has been sent successfully',
        'messageFailed': 'Failed to send message',

        // Debug and Messages
        'accountCreatedSuccessfully':
            'Account created successfully! Please check your email to verify your account.',
        'debug': 'Debug',

        // Authentication Error Messages
        'emailRequired': 'Email is required',
        'invalidEmail': 'Please enter a valid email address',
        'passwordRequired': 'Password is required',
        'passwordMinLength': 'Password must be at least 6 characters',
        'passwordLetterNumber':
            'Password must contain at least one letter and one number',
        'confirmPasswordRequired': 'Please confirm your password',
        'passwordsDoNotMatch': 'Passwords do not match',
        'invalidEmailOrPassword': 'Invalid email or password',
        'checkEmailAddress': 'Please check your email address',
        'checkPassword': 'Please check your password',
        'networkError': 'Network error. Please check your connection.',
        'loginFailed': 'Login failed. Please try again.',
        'emailAlreadyExists': 'An account with this email already exists',
        'passwordRequirementsNotMet': 'Password does not meet requirements',
        'signupRateLimit': 'Too many signup attempts. Please try again later.',
        'configError': 'Configuration error. Please contact support.',
        'signupDisabled': 'Account registration is currently disabled',
        'registrationFailed': 'Registration failed. Please try again.',
        'signingIn': 'Signing in...',
        'creatingAccount': 'Creating account...',
        'welcome': 'Welcome',
        'usernameOrEmail': 'Username or Email',
        'agreeTo': 'By signing up, you agree to our ',
        'termsOfUse': 'Terms of Use',
        'resetPassword': 'Reset Password',
        'forgotPasswordDescription':
            'Enter your email address and we\'ll send you a link to reset your password.',
        'enterEmailAddress': 'Enter your email address',
        'emailExample': 'example@email.com',
        'createAnotherAccount': 'If you want to create another account',
        'signUp': 'Sign Up',

        // Report Detail Screen
        'name': 'Name',
        'explanation': 'Explanation',
        'pleaseEnterName': 'Please enter a name',
        'pleaseEnterReportType': 'Please enter a report type',
        'pleaseEnterType': 'Please enter a type',
        'pleaseEnterReceiverName': 'Please enter receiver name',
        'pleaseEnterObjective': 'Please enter objective',
        'pleaseEnterDescription': 'Please enter description',
        'pleaseEnterImportance': 'Please enter importance',
        'pleaseEnterMainPoints': 'Please enter main points',
        'pleaseEnterSources': 'Please enter information sources',
        'pleaseEnterRoles': 'Please enter roles of actors',
        'pleaseEnterTrends': 'Please enter positive/negative trends',
        'pleaseEnterThemes': 'Please enter taken themes',
        'pleaseEnterImplications': 'Please enter implications/conclusions',
        'pleaseEnterScenarios': 'Please enter scenarios',
        'pleaseEnterFuturePlans': 'Please enter future plans',
        'pleaseEnterApprovingBody': 'Please enter approving body',
        'pleaseEnterSenderName': 'Please enter sender name',
        'pleaseEnterRole': 'Please enter role',
        'pleaseEnterDate': 'Please enter date',
        'failedToSaveProgress': 'Failed to save progress',
        'failedToLoadReport': 'Failed to load report',

        // Edit Profile Validation Messages
        'enterUsername': 'Please enter a username',
        'usernameMinLength': 'Username must be at least 3 characters',
        'usernameMaxLength': 'Username must be at most 20 characters',
        'usernameAllowedChars':
            'Username can only contain letters, numbers, and underscores',
        'enterCurrentPassword': 'Please enter your current password',
        'incorrectPassword': 'Incorrect password',
        'usernameTaken': 'Username is already taken',
        'genericError': 'An error occurred. Please try again.',
        'updating': 'Updating...',
        'newUsername': 'New Username',
        'change': 'Change',
        'currentPasswordRequired': 'Please enter your current password',
        'newPasswordRequired': 'Please enter a new password',
        'passwordTooShort': 'Password must be at least 6 characters',
        'confirmPasswordRequired': 'Please confirm your new password',
        'passwordChangeFailed': 'Failed to change password',
        'changingPassword': 'Changing...',
        'changePassword': 'Change Password',
        'passwordChangedSuccessfully': 'Password changed successfully!',

        // Report History Screen
        'noCompletedReports': 'No completed reports yet.',
        'failedToLoadReports': 'Failed to load reports',
        'untitledReport': 'Untitled Report',
        'notSpecified': 'Not specified',
        'date': 'Date',
        'reportType': 'Report Type',
        'receiver': 'Receiver',
        'sender': 'Sender',
        'objective': 'Objective',
        'attachments': 'Attachments',
        'files': 'file(s)',
        'attached': 'attached',
        'link': 'Link',
        'created': 'Created',
        'completed': 'Completed',
        'edit': 'Edit',
        'view': 'View',
        'close': 'Close',
        'retry': 'Retry',
        'createFirstReport': 'Create Your First Report',

        // PIN Screen
        'enter_pin': 'Enter PIN',
        'set_pin': 'Set PIN',
        'change_pin': 'Change PIN',
        'enter_pin_description': 'Enter your 4-digit PIN to continue',
        'set_pin_description': 'Create a 4-digit PIN to secure your app',
        'change_pin_description': 'Change your existing PIN',
        'incorrect_pin': 'Incorrect PIN. Please try again.',
        'pin_must_be_4_digits': 'PIN must be exactly 4 digits',

        // Report View Screen
        'reportDetails': 'Report Details',
        'completed': 'COMPLETED',
        'basicInformation': 'Basic Information',
        'reportContent': 'Report Content',
        'analysis': 'Analysis',
        'conclusionsFuture': 'Conclusions & Future',
        'reportMetadata': 'Report Metadata',
        'attachments': 'Attachments',
        'fileAttachments': 'File Attachments:',
        'linkAttachment': 'Link Attachment:',
        'reportInformation': 'Report Information',
        'created': 'Created',
        'lastUpdated': 'Last Updated',
        'status': 'Status',
        'at': 'at',

        // Report View Screen
        'reportDetails': 'Report Details',
        'completed': 'COMPLETED',
        'basicInformation': 'Basic Information',
        'reportContent': 'Report Content',
        'analysis': 'Analysis',
        'conclusionsFuture': 'Conclusions & Future',
        'reportMetadata': 'Report Metadata',
        'attachments': 'Attachments',
        'fileAttachments': 'File Attachments:',
        'linkAttachment': 'Link Attachment:',
        'reportInformation': 'Report Information',
        'created': 'Created',
        'lastUpdated': 'Last Updated',
        'status': 'Status',
        'at': 'at',

        // FAQ Screen
        'faq': 'FAQ',
        'contactUs': 'Contact Us',
        'howCreateReport': 'How do I create a report?',
        'whatTypesReports': 'What types of reports can I submit?',
        'howAttachFiles': 'How can I attach files to my report?',
        'canSaveDraft': 'Can I save a draft and continue later?',
        'howViewReports': 'How do I view my submitted reports?',
        'reportApprovalProcess': 'What is the report approval process?',
        'howEditProfile': 'How can I edit my profile?',
        'howChangePassword': 'How do I change my password?',
        'howContactSupport': 'How can I contact support?',
        'faqAnswer':
            'This feature helps you submit detailed reports to the Prosperity Party office with all necessary documentation and attachments.',
        'howCanWeHelp': 'How can we help you?',
        'customerService': 'Customer Service',
        'website': 'Website',
        'facebook': 'Facebook',
        'telegram': 'Telegram',

        // Security Screen
        'changePassword': 'Change Password',
        'termsAndConditions': 'Terms And Conditions',

        // Delete Account Dialog
        'deleteAccountConfirmation':
            'Are you sure you want to delete your account? This action cannot be undone.',

        // Report History
        'noCompletedReports': 'No completed reports yet.',
        'failedToLoadReports': 'Failed to load reports',
        'untitledReport': 'Untitled Report',
        'notSpecified': 'Not specified',
        'date': 'Date',
        'reportType': 'Report Type',
        'receiver': 'Receiver',
        'sender': 'Sender',
        'objective': 'Objective',
        'attachments': 'Attachments',
        'files': 'file(s)',
        'link': 'Link',
        'created': 'Created',
        'completed': 'Completed',
        'edit': 'Edit',
        'view': 'View',
        'close': 'Close',
        'retry': 'Retry',
        'createFirstReport': 'Create Your First Report',
      },
      'am': {
        // App Title
        'appTitle': 'ሐረሪ ዕድገት መተግበሪያ',

        // Common
        'save': 'አስቀምጥ',
        'cancel': 'ዝጋ',
        'next': 'ቀጣይ',
        'back': 'ተመለስ',
        'submit': 'አስገባ',
        'loading': 'በመጫን ላይ...',
        'error': 'ስህተት',
        'success': 'ተሳክቷል',
        'warning': 'ማስጠንቀቂያ',
        'confirm': 'አረጋግጥ',
        'delete': 'ሰርዝ',
        'edit': 'አርትዕ',
        'search': 'ፈልግ',
        'noInternet': 'የኢንተርኔት ግንኙነት የለም',
        'retry': 'እንደገና ይሞክሩ',
        'close': 'ዝጋ',

        // Auth
        'login': 'ግባ',
        'signup': 'ይመዝገቡ',
        'email': 'ኢሜይል',
        'password': 'የይለፍ ቃል',
        'forgotPassword': 'የይለፍ ቃል ረሳኽም?',
        'dontHaveAccount': 'መለያ የሎትም?',
        'alreadyHaveAccount': 'ቀድሞውኑ መለያ አሎት?',
        'loginWithGoogle': 'በ Google ይግቡ',
        'loginWithApple': 'በ Apple ይግቡ',
        'loginWithFacebook': 'በ Facebook ይግቡ',
        'fullName': 'ሙሉ ስም',
        'phoneNumber': 'ስልክ ቁጥር',
        'confirmPassword': 'የይለፍ ቃል አረጋግጥ',
        'createAccount': 'መለያ ይፍጠሩ',
        'termsAgreement': 'በመመዝገብ የኛን',
        'termsOfService': 'የአገልግሎት ውል',
        'privacyPolicy': 'የግላዊነት ፖሊሲ',
        'and': ' እና ',
        'welcomeBack': 'እንኳን በደህና መጡ!',
        'welcomeMessage': 'ለመቀጠል ይግቡ',
        'createNewAccount': 'አዲስ መለያ ይፍጠሩ',
        'registerMessage': 'የእርስዎን መረጃ ከዚህ በታች ያስገቡ ወይም በሶሻል መለያ ይመዝገቡ',
        'alreadyHaveAccountLogin': 'ቀድሞውኑ መለያ አሎት? ይግቡ',
        'forgotPasswordTitle': 'የይለፍ ቃል ረሳሁ',
        'ifYouWantCreateAccount': 'ሌላ መለያ ለመፍጠር ከፈለጉ',
        'orSignUpWith': 'ወይም በሚከተሉት ይመዝገቡ',
        'dontHaveAccountSignUp': 'መለያ የሎትም? ይመዝገቡ',
        'or': 'ወይም',
        'iAcceptTerms': 'ሁሉንም ውሎች እና ሁኔታዎች እቀበላለሁ',

        // Navigation
        'home': 'መነሻ',
        'reports': 'ሪፖርቶች',
        'profile': 'መገለጫ',
        'settings': 'ማስተካከያዎች',
        'language': 'ቋንቋ',
        'logout': 'ውጣ',
        'selectLanguage': 'ቋንቋ ይምረጡ',
        'english': 'English',
        'amharic': 'አማርኛ',
        'oromo': 'Afaan Oromoo',

        // Reports
        'newReport': 'አዲስ ሪፖርት',
        'reportTitle': 'የሪፖርት ርዕስ',
        'reportDescription': 'ገለፃ',
        'reportCategory': 'ምድብ',
        'reportLocation': 'አካባቢ',
        'reportDate': 'ቀን',
        'reportStatus': 'ሁኔታ',
        'reportImages': 'ምስሎች',
        'submitReport': 'ሪፖርት አስገባ',
        'reportSubmitted': 'ሪፖርት ተልኳል',
        'reportSubmittedMessage': 'ሪፖርትዎ በተሳካ ሁኔታ ተልኳል',
        'viewAllReports': 'ሁሉንም ሪፖርቶች ይመልከቱ',
        'myReports': 'የእኔ ሪፖርቶች',
        'noReports': 'ምንም ሪፖርት አልተገኘም',
        'reportDetails': 'የሪፖርት ዝርዝሮች',
        'comments': 'አስተያየቶች',
        'addComment': 'አስተያየት ያስቀምጡ...',
        'post': 'ለጥፍ',
        'like': 'ወደድተዋል',
        'likes': 'ወድጃለሁ',
        'share': 'አካፍል',
        'report': 'ሪፖርት አድርግ',

        // Profile
        'myProfile': 'የእኔ መገለጫ',
        'editProfile': 'መገለጫ አርትዕ',
        'changePassword': 'የይለፍ ቃል ቀይር',
        'accountSettings': 'የመለያ ማስተካከያዎች',
        'helpAndSupport': 'እርዳታ እና ድጋፍ',
        'aboutApp': 'ስለ መተግበሪያው',
        'version': 'ስሪት',
        'logoutConfirmation': 'እርግጠኛ ነህ መውጣት ትፈልጋለህ?',
        'yes': 'አዎ',
        'no': 'አይ',

        // Settings
        'notifications': 'ማሳወቂያዎች',
        'darkMode': 'ጨለማ ሞድ',
        'privacy': 'ግላዊነት',
        'security': 'ደህንነት',
        'termsAndConditions': 'ውሎች እና ሁኔታዎች',
        'rateApp': 'መተግበሪያውን ደረግ ያድርጉት',
        'shareApp': 'መተግበሪያውን አካፍል',
        'clearCache': 'ካሽ አጥፋ',
        'about': 'ስለ',
        'versionInfo': 'የስሪት መረጃ',
        'deleteAccount': 'መለያ ሰርዝ',
        'faq': 'ተደጋጋሚ ጥያቄዎች',

        // Home Screen
        'hello': 'ሰላም',
        'welcomeToHarari':
            'ወደ ሐረሪ ክልላዊ ብልፅግና ፓርቲ የፖለቲካ ትንተና ስርዓት እንኳን በደህና መጡ። ይህ መተግበሪያ ሪፖርት ለማዘጋጀት መመሪያዎችን በመስጠት እና ከሪፖርትዎ ጋር ለማያያዝ እንደ ሰነድ፣ ምስሎች፣ አገናኞች ያሉ አማራጮችን በመስጠት ሪፖርቱን ወደ ብልፅግና ፓርቲ ቢሮ እንዲያካፍሉ ይረዳዎታል።',
        'toSendReport': 'ሪፖርት ለመላክ',
        'clickHere': 'እዚህ ይጫኑ',

        // Authentication
        'alreadyHaveAccountLogin': 'ቀድሞውኑ መለያ አለ��ት? ይግቡ',
        'forgotPasswordTitle': 'የይለፍ ቃል ረሳሁ',
        'ifYouWantCreateAccount': 'ሌላ መለያ መፍጠር ከፈለጉ',
        'orSignUpWith': 'ወይም በሚከተለው ይመዝገቡ',
        'dontHaveAccountSignUp': 'መለያ የለዎትም? ይመዝገቡ',
        'or': 'ወይም',

        // Terms and Conditions
        'termsAndConditionsTitle': 'ውሎች እና ሁኔታዎች',
        'term1': '1. Ea voluptates omnis aut sequi sequi.',
        'term2': '2. Est dolore quce in aliquid ducimus et outem repellendus.',
        'term3': '3. Aut ipsum Quis qui porto quasi aut minus placcati.',
        'term4': '4. Sit consequatur neque do vitae facere.',
        'termBullet1': '- Aut fuga sequi eum voluptatibus provident.',
        'termBullet2':
            '- Eos consequuntur voluptas vel amet eaque aut dignissimos velit.',
        'iAcceptTerms': 'ሁሉንም ውሎች እና ሁኔታዎች እቀበላለሁ',
        'termsDescription':
            'ሐረሪ ዕድገት መተግበሪያን ለመቀጠል እባክዎ የኛን ውሎች እና ሁኔታዎች ያንብቡ እና ያረጋግጡ።',
        'termsPoint1':
            '1. መተግበሪያውን በተገቢ መልክ ለመጠቀም እና ከህጋዊ ህጎች ጋር በመስማማት ያለተግባር ነዎት።',
        'termsPoint2': '2. በሪፖርቶች የሚሰጡ ሁሉም መረጃዎች ትክክለኛ እና እውነተኛ መሆኑ አስፈላጊ ነዎት።',
        'termsPoint3': '3. የመለያ ምስጠራዎን ሚስጥራዊነት ለመጠበቅ እርስዎ ሀላፊ ነዎት።',
        'termsPoint4':
            '4. መተግበሪያው በኛ የግላዊነት ፖሊሲ እንደሚተለቀ የሚለው መረጃ ለማሰባሰብ እና ለማስተካከል ያስችላል።',
        'termsDescription2': 'ይህን መተግበሪያ በመጠቀም እርስዎ የሚስብህየት ነዎት፡-',
        'termsBullet1':
            '- የሐረሪ ክልላዊ ብልፅግና ፓርቲ የፖለቲካ ትንተና ስርዓት ዓላማ እና ተግባር ለማስተያየት።',
        'termsBullet2': '- መተግበሪያውን ለህጋዊ ሪፖርት እና ትንተና ብቻ ለመጠቀም።',
        'termsDescription3':
            'እነዚህ ውሎች ከጊዜ በጊዜ ሊለወጡ ይችላሉ። መተግበሪያውን በመቀጠል ለሚለወጡ ለውጦች መስማማት የሚለው ነዎት።',
        'readTermsMore': 'ለተጨማሪ ዝርዝር መረጃ ድረ-ገጻችን ይመልከቱ ወይም ድጋፍ ያግኙ።',
        'acceptAllTerms': 'ሁሉንም ውሎች እና ሁኔታዎች አንብቤ እቀበላለሁ',
        'acceptContinue': 'እቀበላለሁ እና እንደገና ጀምር',

        // Profile Management
        'changeUsername': 'የተጠቃሚ ስም ቀይር',
        'usernameUpdatedSuccessfully': 'የተጠቃሚ ስም በተሳካ ሁኔታ ተዘምኗል!',
        'passwordSettings': 'የይለፍ ቃል ማስተካከያዎች',
        'passwordChangedSuccessfully': 'የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯ���!',

        // Report Screens
        'reportDetail': 'ዝርዝር',
        'attachment': 'ማያያዣ',
        'finalStep': 'የመጨረሻ ደረጃ',
        'finalStepDescription':
            'የሪፖርትዎን ሁሉንም አስፈላጊ ክፍሎች በተሳካ ሁኔታ አጠናቅቀዋል። ሪፖርትዎን ወደ ብልፅግና ፓርቲ ቢሮ ለማስገባት ጨርስ የሚለውን ይጫኑ።',
        'finish': 'ጨርስ',
        'reportCompletedSuccessfully': 'ሪፖርት በተሳካ ሁኔታ ተጠናቋል!',
        'headingTitle': 'የርዕስ ርዕስ',
        'importanceOfReport': 'የሪፖርት አስፈላጊነት',
        'mainPoints': 'ዋና ነጥቦች',
        'informationSources': 'የመረጃ ምንጮች',
        'rolesOfActors': 'የተዋናዮች እና የባለድርሻ አካላት ሚናዎች',
        'positiveNegativeTrends': 'አዎንታዊ እና አሉታዊ አዝማሚያዎች',
        'takenThemes': 'የተወሰዱ ጭብጦች',
        'implicationsConclusions': 'ተፅእኖዎች እና መደምደሚያዎች',
        'scenarios': 'ሁኔታዎች',
        'futurePlansActivities': 'የወደፊት እቅዶች እና እንቅስቃሴዎች',
        'reportApprovingBody': 'ሪፖርት የሚያፀድቅ አካል',
        'senderName': 'የላኪ ስም',
        'role': 'ሚና',
        'timeMonthDate': 'ጊዜ/ወር/ቀን',
        'file': 'ፋይል',
        'chooseFile': 'ፋይል ምረጥ',
        'link': 'አገናኝ',
        'attachFilesOrLinks': 'ፋይሎች ወይም አገናኞችን ያያይዡ',
        'selectedFiles': 'የተለመዱ ፋይሎች',
        'pasteLinkHere': 'አገናኝ እዚህ ያስቀምጡ',
        'skip': 'ያለለው',
        'failedToPickFiles': 'ፋይሎችን መምረጥ አልተሳካም',
        'noReportIdFound': 'የሪፖርት መለያ አልተገኘም',
        'failedToUploadAttachments': 'ማያያዦችን መስቀል አልተሳካም',

        // Report History
        'view': 'ይመልከቱ',
        'createFirstReport': 'የመጀመሪያ ሪፖርትዎን ይፍጠሩ',

        // Report View
        'completed': 'ተጠናቋል',
        'basicInformation': 'መሰረታዊ መረጃ',
        'reportContent': 'የሪፖርት ይዘት',
        'analysis': 'ትንተና',
        'conclusionsFuture': 'መደምደሚያዎች እና ወደፊት',
        'reportMetadata': 'የሪፖርት ሜታዳታ',
        'attachments': 'ማያያዦች',
        'fileAttachments': 'የፋይል ማያያዦች:',
        'linkAttachment': 'የአገናኝ ማያያዣ:',
        'reportInformation': 'የሪፖርት መረጃ',
        'created': 'ተፈጥሯል',
        'lastUpdated': 'በመጨረሻ ተዘምኗል',
        'status': 'ሁኔታ',
        'reportType': 'የሪፖርት አይነት',
        'type': 'አይነት',
        'receiverName': 'የተቀባይ ስም',
        'objectiveOfReport': 'የሪፖርት አላማ',
        'description': 'ገለፃ',
        'untitledReport': 'ርዕስ የሌለው ሪፖርት',
        'reportDetails': 'የሪፖርት ዝርዝሮች',
        'completed': 'ተጠናቋል',
        'basicInformation': 'መሰረታዊ መረጃ',
        'reportContent': 'የሪፖርት ይዘት',
        'analysis': 'ትንተና',
        'conclusionsFuture': 'መደምደሚያዎች እና ወደፊት',
        'reportMetadata': 'የሪፖርት ሜታዳታ',
        'attachments': 'ማያያዣዎች',
        'fileAttachments': 'የፋይል ማያያዣዎች:',
        'linkAttachment': 'የአገናኝ ማያያዣ:',
        'files': 'ፋይል(ዎች)',
        'receiver': 'ተቀባይ',
        'sender': 'ላኪ',
        'objective': 'ዓላማ',

        // Security
        'securityTitle': 'ደህንነት',
        'deleteAccountTitle': 'መለያ ማጥፋት',
        'deleteAccountMessage': 'መለያዎን ለማጥፋት እርግጠኛ ነዎት? ይህ እርምጃ መግታት አይችሉም።',
        'deleteAccountConfirmation':
            'መለያዎን ለማጥፋት እርግጠኛ ነዎት? ይህ እርምጃ መግታት አይችሉም።',
        'failedToDeleteAccount': 'መለያ ማጥፋት አልተሳካም',
        'changeUsername': 'የተጠቃሚ ስም ቀይር',
        'currentPassword': 'የአሁኑ የይለፍ ቃል',
        'newPassword': 'አዲስ የይለፍ ቃል',
        'confirmNewPassword': 'አዲሱን የይለፍ ቃል አረጋግጥ',
        'passwordRequirements': 'የይለፍ ቃሉ ቢያንስ 8ቱ ቁምፊ እና ቁጥር ሊኖረው ይገባል',
        'passwordMismatch': 'የይለፍ ቃሎች አይዛመዱም',
        'passwordUpdated': 'የይለፍ ቃሉ በተሳካ ሁኔታ ተዘምኗል',
        'usernameUpdated': 'የተጠቃሚ ስም በተሳካ ሁኔታ ተዘምኗል',

        // FAQ & Help Screen
        'faq': 'ተደጋጋሚ ጥያቄዎች',
        'contactUs': 'አግኙን',
        'helpCenter': 'የእርዳታ ማዕከል',
        'contactSupport': 'ድጋፍን ያግኙ',
        'commonQuestions': 'ተደጋጋሚ ጥያቄዎች',
        'troubleshooting': 'ችግሮችን መፍታት',
        'userGuide': 'የተጠቃሚ መመሪያ',
        'videoTutorials': 'የቪዲዮ ማስተማሪያዎች',
        'sendMessage': 'መልእክት ላክ',
        'yourMessage': 'መልእክትዎ...',
        'messageSent': 'መልእክትዎ በተሳካ ሁኔታ ተልኳል',
        'messageFailed': 'መልእክት ላክ አልተሳካም',
        'howCreateReport': 'ሪፖርት እንዴት ማዘጋጀት እችላለሁ?',
        'whatTypesReports': 'ምን ዓይነት ሪፖርቶችን ማስገባት እችላለሁ?',
        'howAttachFiles': 'ለሪፖርቴ ፋይሎችን እንዴት ማያያዝ እችላለሁ?',
        'canSaveDraft': 'አስቀድሜ ያሰሩትን ማስቀመጥ እና በኋላ መቀጠል እችላለሁ?',
        'howViewReports': 'ያስገብተዋልኩትን ሪፖርቶች እንዴት ማየት እችላለሁ?',
        'reportApprovalProcess': 'የሪፖርት ማረጋገጫ ሂደቱ ምን ያህል ይፈጅበታል?',
        'howEditProfile': 'የግሌን መገለጫ እንዴት ማስተካከል እችላለሁ?',
        'howChangePassword': 'የይለፍ ቃሌን እንዴት ልቀይር እችላለሁ?',
        'howContactSupport': 'ድጋፍ እንዴት ልጠይቅ እችላለሁ?',
        'faqAnswer':
            'ይህ ባህሪ ሁሉንም አስፈላጊ ሰነዶች እና ማያያዦች ጋር ወደ ብልፅግና ፓርቲ ቢሮ ዝርዝር ሪፖርቶችን እንዲያስገቡ ይረዳዎታል።',
        'howCanWeHelp': 'በምን እንድንረዳችሁ እንችላለን?',
        'customerService': 'የደንበኞች አገልግሎት',
        'website': 'ድረ-ገጽ',
        'facebook': 'ፌስቡክ',
        'telegram': 'ቴሌግራም',

        // Debug and Messages
        'accountCreatedSuccessfully':
            'መለያ በተሳካ ሁኔታ ተፈጥሯል! መለያዎን ለማረጋገጥ ኢሜይልዎን ይመልከቱ።',
        'debug': 'ዲበግ',

        // Authentication Error Messages
        'emailRequired': 'ኢሜይል ያስፈልጋል',
        'invalidEmail': 'ትክክለኛ ኢሜይል አድራሻ ያስገቡ',
        'passwordRequired': 'የይለፍ ቃል ያስፈልጋል',
        'passwordMinLength': 'የይለፍ ቃሉ ቢያንስ 6 ቁምፊዎች ሊኖሩት ይገባል',
        'passwordLetterNumber': 'የይለፍ ቃሉ ቢያንስ አንድ ፊደል እና አንድ ቁጥር ሊኖረው ይገባል',
        'confirmPasswordRequired': 'እባክዎ የይለፍ ቃልዎን ያረጋግጡ',
        'passwordsDoNotMatch': 'የይለፍ ቃሎች አይዛመዱም',
        'invalidEmailOrPassword': 'ትክክል ያልሆነ ኢሜይል ወይም የይለፍ ቃል',
        'checkEmailAddress': 'እባክዎ የኢሜይል አድራሻዎን ይመልከቱ',
        'checkPassword': 'እባክዎ የይለፍ ቃልዎን ይመልከቱ',
        'networkError': 'የኔትወርክ ስህተት። እባክዎ ግንኙነትዎን ይመልከቱ።',
        'loginFailed': 'መግባት አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
        'emailAlreadyExists': 'በዚህ ኢሜይል መለያ አስቀድሞ አለ',
        'passwordRequirementsNotMet': 'የይለፍ ቃሉ መስፈርቶችን አያሟላም',
        'signupRateLimit': 'ብዙ የመመዝገቢያ ሙከራዎች። እባክዎ በኋላ ይሞክሩ።',
        'configError': 'የማዋቀሪያ ስህተት። እባክዎ ድጋፍን ያግኙ።',
        'signupDisabled': 'የመለያ ምዝገባ በአሁኑ ጊዜ ተሰናክሏል',
        'registrationFailed': 'ምዝገባ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
        'signingIn': 'በመግባት ላይ...',
        'creatingAccount': 'መለያ በመፍጠር ላይ...',
        'welcome': 'እንኳን ደህና መጡ',
        'usernameOrEmail': 'የተጠቃሚ ስም ወይም ኢሜይል',
        'agreeTo': 'በመመዝገብ የኛን ',
        'termsOfUse': 'የአጠቃቀም ውሎች',
        'resetPassword': 'የይለፍ ቃል ዳግም አስተካክል',
        'forgotPasswordDescription':
            'የኢሜይል አድራሻዎን ያስገቡ እና የይለፍ ቃልዎን ዳግም ለማስተካከል አገናኝ እንልክልዎታለን።',
        'enterEmailAddress': 'የኢሜይል አድራሻዎን ያስገቡ',
        'emailExample': 'ምሳሌ@ኢሜይል.com',
        'createAnotherAccount': 'ሌላ መለያ መፍጠር ከፈለጉ',
        'signUp': 'ይመዝገቡ',

        // Report Detail Screen
        'name': 'ስም',
        'explanation': 'ማብራሪያ',
        'pleaseEnterName': 'እባክዎ ስም ያስገቡ',
        'pleaseEnterReportType': 'እባክዎ የሪፖርት አይነት ያስገቡ',
        'pleaseEnterType': 'እባክዎ አይነት ያስገቡ',
        'pleaseEnterReceiverName': 'እባክዎ የተቀባይ ስም ያስገቡ',
        'pleaseEnterObjective': 'እባክዎ አላማ ያስገቡ',
        'pleaseEnterDescription': 'እባክዎ ገለፃ ያስገቡ',
        'pleaseEnterImportance': 'እባክዎ አስፈላጊነት ያስገቡ',
        'pleaseEnterMainPoints': 'እባክዎ ዋና ነጥቦች ያስገቡ',
        'pleaseEnterSources': 'እባክዎ የመረጃ ምንጮች ያስገቡ',
        'pleaseEnterRoles': 'እባክዎ የተዋናዮች ሚናዎች ያስገቡ',
        'pleaseEnterTrends': 'እባክዎ አዎንታዊ/አሉታዊ አዝማሚያዎች ያስገቡ',
        'pleaseEnterThemes': 'እባክዎ የተወሰዱ ጭብጦች ያስገቡ',
        'pleaseEnterImplications': 'እባክዎ ተፅእኖዎች/መደምደሚያዎች ያስገቡ',
        'pleaseEnterScenarios': 'እባክዎ ሁኔታዎች ያስገቡ',
        'pleaseEnterFuturePlans': 'እባክዎ የወደፊት እቅዶች ያስገቡ',
        'pleaseEnterApprovingBody': 'እባክዎ የሚያፀድቅ አካል ያስገቡ',
        'pleaseEnterSenderName': 'እባክዎ የላኪ ስም ያስገቡ',
        'pleaseEnterRole': 'እባክዎ ሚና ያስገቡ',
        'pleaseEnterDate': 'እባክዎ ቀን ያስገቡ',
        'failedToSaveProgress': 'ሂደት ማስቀመጥ አልተሳካም',
        'failedToLoadReport': 'ሪፖርት መጫን አልተሳካም',

        // Edit Profile Validation Messages
        'enterUsername': 'እባክዎ የተጠቃሚ ስም ያስገቡ',
        'usernameMinLength': 'የተጠቃሚ ስም ቢያንስ 3 ቁምፊዎች ሊኖረው ይገባል',
        'usernameMaxLength': 'የተጠቃሚ ስም ቢያንስ 20 ቁምፊዎች ሊኖረው ይገባል',
        'usernameAllowedChars': 'የተጠቃሚ ስም ፊደሎች፣ ቁጥሮች እና አንድ ላይ ብቻ ሊኖረው ይገባል',
        'enterCurrentPassword': 'እባክዎ የአሁኑ የይለፍ ቃል ያስገቡ',
        'incorrectPassword': 'ትክክል ያልሆነ የይለፍ ቃል',
        'usernameTaken': 'የተጠቃሚ ስም ቀድሞ ተወስዷል',
        'genericError': 'ስህተት ተስቷል። እባክዎ እንደገና ይሞክሩ።',
        'updating': 'በማዘምን ላይ...',
        'newUsername': 'አዲስ የተጠቃሚ ስም',
        'change': 'ቀይር',
        'currentPasswordRequired': 'እባክዎ የአሁኑ የይለፍ ቃል ያስገቡ',
        'newPasswordRequired': 'እባክዎ አዲስ የይለፍ ቃል ያስገቡ',
        'passwordTooShort': 'የይለፍ ቃሉ ቢያንስ 6 ቁምፊዎች ሊኖረው ይገባል',
        'confirmPasswordRequired': 'እባክዎ አዲሱን የይለፍ ቃል ያረጋግጡ',
        'passwordChangeFailed': 'የይለፍ ቃል መቀየር አልተሳካም',
        'changingPassword': 'በመቀየር ላይ...',
        'changePassword': 'የይለፍ ቃል ቀይር',
        'passwordChangedSuccessfully': 'የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል!',

        // Report History Screen
        'noCompletedReports': 'ገና የተጠናቀቁ ሪፖርቶች የሉም።',
        'failedToLoadReports': 'ሪፖርቶችን መጫን አልተሳካም',
        'untitledReport': 'ርዕስ የሌለው ሪፖርት',
        'notSpecified': 'አልተገለጸም',
        'date': 'ቀን',
        'reportType': 'የሪፖርት አይነት',
        'receiver': 'ተቀባይ',
        'sender': 'ላኪ',
        'objective': 'ዓላማ',
        'attachments': 'ማያያዦች',
        'files': 'ፋይል(ዎች)',
        'attached': 'የተለጠፈ',
        'link': 'አገናኝ',
        'created': 'ተፈጥሯል',
        'completed': 'ተጠናቋል',
        'edit': 'አርትዕ',
        'view': 'ይመልከቱ',
        'close': 'ዝጋ',
        'retry': 'እንደገና ይሞክሩ',
        'createFirstReport': 'የመጀመሪያ ሪፖርትዎን ይፍጠሩ',

        // PIN Screen
        'enter_pin': 'ፒን ያስገቡ',
        'set_pin': 'ፒን ያስተካክሉ',
        'change_pin': 'ፒን ቀይር',
        'enter_pin_description': 'ለመቀጠል 4 አሃዞች ፒን ያስገቡ',
        'set_pin_description': 'መተግበሪያዎን ለማስተካከል 4 አሃዞች ፒን ይፍጠሩ',
        'change_pin_description': 'የእርስዎን ፒን ቀይር',
        'incorrect_pin': 'ትክክል ያልሆነ ፒን። እባክዎ እንደገና ይሞክሩ።',
        'pin_must_be_4_digits': 'ፒን በትክክል 4 አሃዞች መሆኑ አስፈላጊ ነዎት',

        // Report View Screen
        'reportDetails': 'የሪፖርት ዝርዝሮች',
        'completed': 'ተጠናቋል',
        'basicInformation': 'መሰረታዊ መረጃ',
        'reportContent': 'የሪፖርት ይዘት',
        'analysis': 'ትንተና',
        'conclusionsFuture': 'መደምደሚያዎች እና ወደፊት',
        'reportMetadata': 'የሪፖርት ሜታዳታ',
        'attachments': 'ማያያዦች',
        'fileAttachments': 'የፋይል ማያያዦች:',
        'linkAttachment': 'የአገናኝ ማያያዣ:',
        'reportInformation': 'የሪፖርት መረጃ',
        'created': 'ተፈጥሯል',
        'lastUpdated': 'በመጨረሻ ተዘምኗል',
        'status': 'ሁኔታ',
        'at': 'በ',

        // Report View Screen
        'reportDetails': 'የሪፖርት ዝርዝሮች',
        'completed': 'ተጠናቋል',
        'basicInformation': 'መሰረታዊ መረጃ',
        'reportContent': 'የሪፖርት ይዘት',
        'analysis': 'ትንተና',
        'conclusionsFuture': 'መደምደሚያዎች እና ወደፊት',
        'reportMetadata': 'የሪፖርት ሜታዳታ',
        'attachments': 'ማያያዦች',
        'fileAttachments': 'የፋይል ማያያዦች:',
        'linkAttachment': 'የአገናኝ ማያያዣ:',
        'reportInformation': 'የሪፖርት መረጃ',
        'created': 'ተፈጥሯል',
        'lastUpdated': 'በመጨረሻ ተዘምኗል',
        'status': 'ሁኔታ',
        'at': 'በ',
      },
      'om': {
        // App Title
        'appTitle': 'Appii Fayyadama Hararii',

        // Common
        'save': 'Qabadhu',
        'cancel': 'Dhiisi',
        'next': 'Itaana',
        'back': 'Deebi\'i',
        'submit': 'Galchi',
        'loading': 'Oofii itti fufuun jira...',
        'error': 'Dogoggora',
        'success': 'Milkaa\'e',
        'warning': 'Dinnqinaaf',
        'confirm': 'Mirkaneessi',
        'delete': 'Haquu',
        'edit': 'Jijjiiri',
        'search': 'Barbaadi',
        'noInternet': 'Waan internettiin walqunnamtii hin jiru',
        'retry': 'Irra deebi\'i',
        'close': 'Cufi',

        // Auth
        'login': 'Seeni',
        'signup': 'Galmaa\'i',
        'email': 'Imeelii',
        'password': 'Jecha Iccitii',
        'forgotPassword': 'Jecha icciitii irraa darbee jirtaa?',
        'dontHaveAccount': 'Akkaawuntii hin qabduu?',
        'alreadyHaveAccount': 'Akkaawuntii qabdaa?',
        'loginWithGoogle': 'Google\'n seeni',
        'loginWithApple': 'Apple\'n seeni',
        'loginWithFacebook': 'Facebook\'n seeni',
        'fullName': 'Maqaa Guutuu',
        'phoneNumber': 'Lakkoofsa Bilbila',
        'confirmPassword': 'Jecha Iccitii Mirkaneessi',
        'createAccount': 'Akkaawuntii Uumuu',
        'termsAgreement': 'Galmaa\'uudhaan, waliigala',
        'termsOfService': 'Seerawwan Tajaajilaa',
        'privacyPolicy': 'Ijaarsa Ibsa Addaa',
        'and': 'fi',
        'welcomeBack': 'Baga Nagaan Dhufte!',
        'welcomeMessage': 'Itti fufuuf seeni',
        'createNewAccount': 'Akkaawuntii Haaraa Uumuu',
        'registerMessage':
            'Odeeffannoo keessan gadi bu\'iinsa keessanii galchaa ykn akkaawuntii hawaasaatiin galmaa\'aa',
        'alreadyHaveAccountLogin': 'Akkaawuntii qabdaa? Seeni',
        'forgotPasswordTitle': 'Jecha Iccitii Irraanfadhe',
        'ifYouWantCreateAccount': 'Akkaawuntii biraa uumuu yoo barbaaddan',
        'orSignUpWith': 'ykn kanaan galmaa\'aa',
        'dontHaveAccountSignUp': 'Akkaawuntii hin qabduu? Galmaa\'aa',
        'or': 'ykn',
        'iAcceptTerms': 'Haala fi heerri hunda nan fudhaa',

        // Navigation
        'home': 'Mana',
        'reports': 'Odeeffannoo',
        'profile': 'Seenaa',
        'settings': 'Sirreeffama',
        'language': 'Afaan',
        'logout': 'Ba\'i',
        'selectLanguage': 'Afaan Filadhu',
        'english': 'English',
        'amharic': 'Amariffaa',
        'oromo': 'Afaan Oromoo',

        // Reports
        'newReport': 'Odeeffannoo Haaraa',
        'reportTitle': 'Maqaa Odeeffannoo',
        'reportDescription': 'Ibsa',
        'reportCategory': 'Gareen',
        'reportLocation': 'Bakka',
        'reportDate': 'Guyyaa',
        'reportStatus': 'Haala',
        'reportImages': 'Suurawwan',
        'submitReport': 'Odeeffannoo Galchi',
        'reportSubmitted': 'Odeeffannoo Galfame',
        'reportSubmittedMessage': 'Odeeffannoo keessan milkaa\'inaan galfame',
        'viewAllReports': 'Odeeffannoo Hunda Ilaali',
        'myReports': 'Odeeffannoo Koo',
        'noReports': 'Odeeffannoo hin argamne',
        'reportDetails': 'Garuurri Odeeffannoo',
        'comments': 'Yaada',
        'addComment': 'Yaada dabaladhu...',
        'post': 'Baasi',
        'like': 'Jaalladha',
        'likes': 'Jaallatamaa',
        'share': 'Qoodi',
        'report': 'Odeeffannoo',

        // Profile
        'myProfile': 'Seenaa Koo',
        'editProfile': 'Seenaa Jijjiiri',
        'changePassword': 'Jecha Iccitii Jijjiiri',
        'accountSettings': 'Sirreeffama Akkaawuntii',
        'helpAndSupport': 'Gargaarsa fi Deeggarsa',
        'aboutApp': 'Waa\'ee Appii',
        'version': 'Faayila',
        'logoutConfirmation': 'Dhugumatti ba\'uu barbaadda?',
        'yes': 'Eeyyee',
        'no': 'Lakki',

        // Settings
        'notifications': 'Beeksisa',
        'darkMode': 'Moodii Gurraacha',
        'privacy': 'Ibsa Addaa',
        'security': 'Tiksummaa',
        'termsAndConditions': 'Haala fi Heera',
        'rateApp': 'Appii Madaaluu',
        'shareApp': 'Appii Qoodi',
        'clearCache': 'Qabiyyee Cufaa Adii',
        'about': 'Waa\'ee',
        'versionInfo': 'Odeeffannoo Faayilaa',
        'deleteAccount': 'Akkaawuntii Haquu',
        'faq': 'Gaaffii Deebii',

        // Home Screen
        'hello': 'AKKAM',
        'welcomeToHarari':
            'Gara Sirna Xiinxala Siyaasaa Paartii Badhaadhinaa Naannoo Hararii baga nagaan dhuftan. Appiin kun gabaasa qopheessuuf qajeelfama kennuudhaan fi gabaasa keessan waliin qabsiisuu dandeessan akka galmee, suuraa, hidhannoo fi kkf filannoo kennuudhaan gara waajjira paartii badhaadhinaatti gabaasa qooduuf isin gargaara.',
        'toSendReport': 'GABAASA ERGUU',
        'clickHere': 'ASITTI CUQAASAA',

        // Authentication
        'alreadyHaveAccountLogin': 'Akkaawuntii qabdaa? Seeni',
        'forgotPasswordTitle': 'Jecha Iccitii Irraanfadhe',
        'ifYouWantCreateAccount': 'Akkaawuntii biraa uumuu yoo barbaaddan',
        'orSignUpWith': 'ykn kanaan galmaa\'aa',
        'dontHaveAccountSignUp': 'Akkaawuntii hin qabduu? Galmaa\'aa',
        'or': 'ykn',

        // Terms and Conditions
        'termsAndConditionsTitle': 'Haala fi Heera',
        'term1': '1. Ea voluptates omnis aut sequi sequi.',
        'term2': '2. Est dolore quce in aliquid ducimus et outem repellendus.',
        'term3': '3. Aut ipsum Quis qui porto quasi aut minus placcati.',
        'term4': '4. Sit consequatur neque do vitae facere.',
        'termBullet1': '- Aut fuga sequi eum voluptatibus provident.',
        'termBullet2':
            '- Eos consequuntur voluptas vel amet eaque aut dignissimos velit.',
        'iAcceptTerms': 'Haala fi heera hunda nan fudhaa',
        'termsDescription':
            'Appii Fayyadama Hararii itti fufuuf haala fi heera keenya dubbisi fi mirkaneessi.',
        'termsPoint1':
            '1. Appiin kun sirriitti fayyadamuu fi seera biyyaa waliin walqunnamuu qabda.',
        'termsPoint2':
            '2. Gabaasa keessatti argaman odeeffannoo hundi dhugaa fi sirrii ta\'uu qaba.',
        'termsPoint3':
            '3. Odeeffannoo akkawuntii keessan tiksummaa eeguun isin irra ga\'a.',
        'termsPoint4':
            '4. Appiin kun odeeffannoo keenya ijaarsa ibsa addaa keessatti ibsamee walitti qabu fi jijjiira.',
        'termsDescription2': 'Appii kana fayyadamuudhaan, ati hubatta:',
        'termsBullet1':
            '- Kaayyoo fi hojii Sirna Xiinxala Siyaasaa Paartii Badhaadhinaa Naannoo Hararii hubattu.',
        'termsBullet2':
            '- Appii kana gabaasa sirrii fi xiinxalaaf qofa fayyadamtu.',
        'termsDescription3':
            'Haala kana yeroo yerootti jijjiiruu ni danda\'a. Appii kana itti fufuun jijjiiramaaf walii galuu agarsiisa.',
        'readTermsMore':
            'Odeeffannoo bal\'inaan argachuuf saayitii keenya ilaali ykn gargaarsa qunnamaa.',
        'acceptAllTerms': 'Haala fi heera hunda dubbisee fi nan fudhaa',
        'acceptContinue': 'Fudhi fi Iti fufi',

        // Profile Management
        'changeUsername': 'Maqaa Fayyadamaa Jijjiiri',
        'usernameUpdatedSuccessfully':
            'Maqaan fayyadamaa milkaa\'inaan haaromfame!',
        'passwordSettings': 'Qindaa\'ina Jecha Iccitii',
        'passwordChangedSuccessfully':
            'Jecha iccitii milkaa\'inaan jijjiirame!',

        // Report Screens
        'reportDetail': 'Bal\'ina',
        'attachment': 'Qabsiisa',
        'finalStep': 'Tarkaanfii Dhumaa',
        'finalStepDescription':
            'Kutaalee barbaachisoo gabaasa keessanii hunda milkaa\'inaan xumurtan. Gabaasa keessan gara waajjira Paartii Badhaadhinaatti galchuuf Xumuri jedhaa cuqaasaa.',
        'finish': 'Xumuri',
        'reportCompletedSuccessfully': 'Gabaasni milkaa\'inaan xumurame!',
        'headingTitle': 'Mata duree mataa',
        'importanceOfReport': 'Barbaachisummaa Gabaasaa',
        'mainPoints': 'Qabxiilee ijoo',
        'informationSources': 'Maddoota Odeeffannoo',
        'rolesOfActors': 'Gahee taphattoota fi qooda fudhattootaa',
        'positiveNegativeTrends': 'Adeemsa gaarii fi hamaa',
        'takenThemes': 'Mata dureewwan fudhataman',
        'implicationsConclusions': 'Dhiibbaa fi Xumura',
        'scenarios': 'Haala',
        'futurePlansActivities': 'Karoora fi sochiiwwan gara fuulduraatti',
        'reportApprovingBody': 'Qaama gabaasa mirkaneessu',
        'senderName': 'Maqaa Ergituu',
        'role': 'Gahee',
        'timeMonthDate': 'Sa\'aatii/Ji\'a/Guyyaa',
        'file': 'FAAYILII',
        'chooseFile': 'Faayilii Filadhu',
        'link': 'HIDHANNOO',
        'attachFilesOrLinks': 'Faayilota ykn Hidhannoowwan Qabsiisi',
        'selectedFiles': 'Faayilota Filataman',
        'pasteLinkHere': 'Hidhannoo asitti maxxansi',
        'skip': 'Irra Utuu',
        'failedToPickFiles': 'Faayilota filachuun hin milkoofne',
        'noReportIdFound': 'Gabaasa ID hin argamne',
        'failedToUploadAttachments': 'Qabsiisoota ol kaasuun hin milkoofne',

        // Report History
        'view': 'Ilaali',
        'createFirstReport': 'Gabaasa Jalqabaa Keessan Uumaa',

        // Report View
        'completed': 'XUMURAME',
        'basicInformation': 'Odeeffannoo Bu\'uuraa',
        'reportContent': 'Qabiyyee Gabaasaa',
        'analysis': 'Xiinxala',
        'conclusionsFuture': 'Xumura fi Fuuldura',
        'reportMetadata': 'Meetaadeetaa Gabaasaa',
        'attachments': 'Qabsiisoota',
        'fileAttachments': 'Qabsiisoota Faayilii:',
        'linkAttachment': 'Qabsiisa Hidhannoo:',
        'reportInformation': 'Odeeffannoo Gabaasaa',
        'created': 'Uumame',
        'lastUpdated': 'Dhumatti Haaromfame',
        'status': 'Haala',
        'reportType': 'Gosa Gabaasaa',
        'type': 'Gosa',
        'receiverName': 'Maqaa Fudhattuu',
        'objectiveOfReport': 'Kaayyoo Gabaasaa',
        'description': 'Ibsa',
        'untitledReport': 'Gabaasa Mata duree hin qabne',
        'reportDetails': 'Gabaasa Keessaa',
        'completed': 'Xumurame',
        'basicInformation': 'Odeeffannoo Bu\'uuraa',
        'reportContent': 'Qabiyyee Gabaasaa',
        'analysis': 'Xiinxala',
        'conclusionsFuture': 'Xumura fi Fuuldura',
        'reportMetadata': 'Meetaadeetaa Gabaasaa',
        'attachments': 'Qabsiisoota',
        'fileAttachments': 'Qabsiisoota Faayilii:',
        'linkAttachment': 'Qabsiisa Hidhannoo:',
        'files': 'faayilii(wwan)',
        'receiver': 'Fudhattuu',
        'sender': 'Ergaa',
        'objective': 'Kaayyoo',

        // Security
        'securityTitle': 'Daqiiqaa',
        'deleteAccountTitle': 'Akkaawuntii Haquu',
        'deleteAccountMessage':
            'Akkaawuntii keessan haquu ni jaallattaa? Gochaan kun deebifamuun hin danda\'amu.',
        'failedToDeleteAccount': 'Akkaawuntii haquu hin dandeenye',
        'changeUsername': 'Maqaa Fayyadamtaa Jijjiiri',
        'currentPassword': 'Jecha Iccitii Ammaa',
        'newPassword': 'Jecha Iccitii Haaraa',
        'confirmNewPassword': 'Jecha Iccitii Haaraa Mirkaneessi',
        'passwordRequirements':
            'Jecha icciitii keessan dheeraansaan sadarkaa 8 qabaachuun waliin lakkoofsas qabaachuu qaba',
        'passwordMismatch': 'Jecha icciitiin wal hin gitu',
        'passwordUpdated': 'Jecha icciitiin milkaa\'inaan jijjiirame',
        'usernameUpdated': 'Maqaan fayyadamtaa milkaa\'inaan jijjiirame',
        'changePassword': 'Jecha Iccitii Jijjiiri',
        'termsAndConditions': 'Haala fi Heera',

        // FAQ & Help Screen
        'faq': 'Gaaffilee Dabalataan',
        'contactUs': 'Nu Qunnamti',
        'helpCenter': 'Giddugala Gargaarsa',
        'contactSupport': 'Gargaarsa Qunnamti',
        'commonQuestions': 'Gaaffilee Dabalataan',
        'tursing': 'Rakkoo Fursuudhaan',
        'userGuide': 'Qajeelfama Fayyadamtaa',
        'videoTutorials': 'Barsiisota Vidiyoo',
        'sendMessage': 'Ergaa',
        'yourMessage': 'Ergaa kee...',
        'messageSent': 'Ergaa kee milkaa\'inaan erge',
        'messageFailed': 'Ergaa hin dandeenye',
        'howCreateReport': 'Akkamittin gabaasa uumuu danda\'a?',
        'whatTypesReports': 'Gosa gabaasaa meeqa naan gabaasuu danda\'a?',
        'howAttachFiles':
            'Faayilota gabaasa koottiin walitti qabsiisuu akkamitti danda\'a?',
        'canSaveDraft':
            'Duraan hojjette kana eegachuun itti fufuu nan danda\'aa?',
        'howViewReports': 'Gabaasaa dhiyeesite akkamitti ilaaluu danda\'a?',
        'reportApprovalProcess':
            'Gabaasa mirkaneessuu keessatti wantoota maal jiran?',
        'howEditProfile': 'Seenaa koo akkamitti jijjiiruu danda\'a?',
        'howChangePassword':
            'Jecha icciitiin koo akkamitti jijjiiruu danda\'a?',
        'howContactSupport': 'Tumsa akkamitti qunnamuu danda\'a?',
        'faqAnswer':
            'Amalli kun galmee fi qabsiisoota barbaachisoo hunda waliin gabaasa bal\'inaan qaban gara waajjira Paartii Badhaadhinaatti akka galchitan isin gargaara.',
        'howCanWeHelp': 'Akkam akka isin gargaarruu dandeenyaa?',
        'customerService': 'Tajaajila Fayyadamtoota',
        'website': 'Weebsaayitii',
        'facebook': 'Feebookii',
        'telegram': 'Teelogramii',
        'faqHelp': 'Gaaffii Deebii fi Gargaarsa',
        'faqDescription':
            'Amalli kun galmee fi qabsiisoota barbaachisoo hunda waliin gabaasa bal\'inaan qaban gara waajjira Paartii Badhaadhinaatti akka galchitan isin gargaara.',
        'noCompletedReports': 'Gabaasni xumuramaa hin jiru',
        'failedToLoadReports': 'Gabaasota fayyadamaa hin danda\'amne',
        'untitledReport': 'Gabaasa mata duree hin qabne',
        'notSpecified': 'Kan hin murtoofne',
        'date': 'Guyyaa',
        'reportType': 'Gosa Gabaasaa',
        'receiver': 'Fudhattuu',
        'sender': 'Ergaa',
        'objective': 'Kaayyoo',
        'attachments': 'Qabsiisoota',
        'files': 'Faayilota',
        'link': 'Hidhannoo',
        'created': 'Uumame',
        'completed': 'Xumurame',
        'edit': 'Jijjiiri',
        'view': 'Ilaali',
        'retry': 'Irra deebi\'i',
        'createFirstReport': 'Gabaasa Jalqabaa Keessan Uumaa',

        // Debug and Messages
        'accountCreatedSuccessfully':
            'Akkaawuntiin milkaa\'inaan uumame! Akkaawuntii keessan mirkaneessuuf imeelii keessan ilaali.',
        'debug': 'Diibaagii',

        // Authentication Error Messages
        'emailRequired': 'Imeeliin barbaachisaa dha',
        'invalidEmail': 'Imeelii sirrii ta\'e galchaa',
        'passwordRequired': 'Jecha icciitii barbaachisaa dha',
        'passwordMinLength':
            'Jecha icciitii yoo xiqqaate arfii 6 qabaachuu qaba',
        'passwordLetterNumber':
            'Jecha icciitii yoo xiqqaate qubee tokko fi lakkoofsa tokko qabaachuu qaba',
        'confirmPasswordRequired': 'Jecha icciitii keessan mirkaneessaa',
        'passwordsDoNotMatch': 'Jecha icciitiin wal hin gitu',
        'invalidEmailOrPassword': 'Imeelii ykn jecha icciitii sirrii miti',
        'checkEmailAddress': 'Teessoo imeelii keessan ilaalaa',
        'checkPassword': 'Jecha icciitii keessan ilaalaa',
        'networkError': 'Dogoggora networkii. Walqunnamtii keessan ilaalaa.',
        'loginFailed': 'Seenuun hin milkoofne. Irra deebi\'aa yaali.',
        'emailAlreadyExists': 'Imeelii kanaan akkaawuntiin duraan jira',
        'passwordRequirementsNotMet': 'Jecha icciitiin ulaagaa hin guutne',
        'signupRateLimit':
            'Yaalii galmaa\'uu baay\'ee. Booda irra deebi\'aa yaali.',
        'configError': 'Dogoggora qindaa\'inaa. Gargaarsa qunnamaa.',
        'signupDisabled': 'Galmaa\'uun akkaawuntii yeroo ammaa cufameera',
        'registrationFailed':
            'Galmaa\'uun hin milkoofne. Irra deebi\'aa yaali.',
        'signingIn': 'Seenaa jira...',
        'creatingAccount': 'Akkaawuntii uumaa jira...',
        'welcome': 'Baga nagaan dhufte',
        'usernameOrEmail': 'Maqaa fayyadamaa ykn Imeelii',
        'agreeTo': 'Galmaa\'uudhaan, keenya ',
        'termsOfUse': 'Haala Fayyadamaa',
        'resetPassword': 'Jecha Icciitii Irra Deebi\'i',
        'forgotPasswordDescription':
            'Teessoo imeelii keessan galchaa, jecha icciitii keessan irra deebi\'uuf hidhannoo isiniif ergina.',
        'enterEmailAddress': 'Teessoo imeelii keessan galchaa',
        'emailExample': 'fakkeenyaa@imeelii.com',
        'createAnotherAccount': 'Akkaawuntii biraa uumuu yoo barbaaddan',
        'signUp': 'Galmaa\'aa',

        // Report Detail Screen
        'name': 'Maqaa',
        'explanation': 'Ibsa',
        'pleaseEnterName': 'Maqaa galchaa',
        'pleaseEnterReportType': 'Gosa gabaasaa galchaa',
        'pleaseEnterType': 'Gosa galchaa',
        'pleaseEnterReceiverName': 'Maqaa fudhattuu galchaa',
        'pleaseEnterObjective': 'Kaayyoo galchaa',
        'pleaseEnterDescription': 'Ibsa galchaa',
        'pleaseEnterImportance': 'Barbaachisummaa galchaa',
        'pleaseEnterMainPoints': 'Qabxiilee ijoo galchaa',
        'pleaseEnterSources': 'Maddoota odeeffannoo galchaa',
        'pleaseEnterRoles': 'Gahee taphattoota galchaa',
        'pleaseEnterTrends': 'Adeemsa gaarii fi hamaa galchaa',
        'pleaseEnterThemes': 'Mata dureewwan fudhataman galchaa',
        'pleaseEnterImplications': 'Dhiibbaa fi xumura galchaa',
        'pleaseEnterScenarios': 'Haala galchaa',
        'pleaseEnterFuturePlans':
            'Karoora fi sochiiwwan gara fuulduraatti galchaa',
        'pleaseEnterApprovingBody': 'Qaama mirkaneessu galchaa',
        'pleaseEnterSenderName': 'Maqaa ergituu galchaa',
        'pleaseEnterRole': 'Gahee galchaa',
        'pleaseEnterDate': 'Guyyaa galchaa',
        'failedToSaveProgress': 'Adeemsa qabachuu hin dandeenye',
        'failedToLoadReport': 'Gabaasa fe\'uu hin dandeenye',

        // Edit Profile Validation Messages
        'enterUsername': 'Maqaa fayyadamaa galchaa',
        'usernameMinLength':
            'Maqaan fayyadamaa yoo xiqqaate arfii 3 qabaachuu qaba',
        'usernameMaxLength':
            'Maqaan fayyadamaa yoo xiqqaate arfii 20 qabaachuu qaba',
        'usernameAllowedChars':
            'Maqaan fayyadamaa qubee, lakkoofsa fi mallattoo tokko tokko qofaan qabaachuu qaba',
        'enterCurrentPassword': 'Jecha icciitii ammaa galchaa',
        'incorrectPassword': 'Jecha icciitii sirrii miti',
        'usernameTaken': 'Maqaan fayyadamaa duraan fudhatame',
        'genericError': 'Dogoggora uumame. Irra deebi\'aa yaali.',
        'updating': 'Haaromfamaa jira...',
        'newUsername': 'Maqaa Fayyadamaa Haaraa',
        'change': 'Jijjiiri',
        'currentPasswordRequired': 'Jecha icciitii ammaa galchaa',
        'newPasswordRequired': 'Jecha icciitii haaraa galchaa',
        'passwordTooShort':
            'Jecha icciitii yoo xiqqaate arfii 6 qabaachuu qaba',
        'confirmPasswordRequired': 'Jecha icciitii haaraa mirkaneessaa',
        'passwordChangeFailed': 'Jecha icciitii jijjiiruu hin dandeenye',
        'changingPassword': 'Jijjiiramuu jira...',
        'changePassword': 'Jecha Iccitii Jijjiiri',
        'passwordChangedSuccessfully':
            'Jecha icciitii milkaa\'inaan jijjiirame!',

        // Report History Screen
        'noCompletedReports': 'Gabaasni xumuramaa hin jiru.',
        'failedToLoadReports': 'Gabaasota fe\'uu hin dandeenye',
        'untitledReport': 'Gabaasa mata duree hin qabne',
        'notSpecified': 'Kan hin murtoofne',
        'date': 'Guyyaa',
        'reportType': 'Gosa Gabaasaa',
        'receiver': 'Fudhattuu',
        'sender': 'Ergaa',
        'objective': 'Kaayyoo',
        'attachments': 'Qabsiisoota',
        'files': 'faayilii(wwan)',
        'attached': 'qabsiifame',
        'link': 'Hidhannoo',
        'created': 'Uumame',
        'completed': 'Xumurame',
        'edit': 'Jijjiiri',
        'view': 'Ilaali',
        'close': 'Cufi',
        'retry': 'Irra deebi\'i',
        'createFirstReport': 'Gabaasa Jalqabaa Keessan Uumaa',

        // PIN Screen
        'enter_pin': 'PIN galchi',
        'set_pin': 'PIN qindeessi',
        'change_pin': 'PIN jijjiiri',
        'enter_pin_description': 'Itti fufuuf PIN lakkoofsa 4 galchi',
        'set_pin_description':
            'Appii keessan tiksummaa gochuuf PIN lakkoofsa 4 uumaa',
        'change_pin_description': 'PIN keessan jijjiiri',
        'incorrect_pin': 'PIN sirrii miti. Irra deebi\'aa yaali.',
        'pin_must_be_4_digits': 'PIN lakkoofsa 4 qofa ta\'uu qaba',

        // Report View Screen
        'reportDetails': 'Bal\'ina Gabaasaa',
        'completed': 'XUMURAME',
        'basicInformation': 'Odeeffannoo Bu\'uuraa',
        'reportContent': 'Qabiyyee Gabaasaa',
        'analysis': 'Xiinxala',
        'conclusionsFuture': 'Xumura fi Fuuldura',
        'reportMetadata': 'Meetaadeetaa Gabaasaa',
        'attachments': 'Qabsiisoota',
        'fileAttachments': 'Qabsiisoota Faayilii:',
        'linkAttachment': 'Qabsiisa Hidhannoo:',
        'reportInformation': 'Odeeffannoo Gabaasaa',
        'created': 'Uumame',
        'lastUpdated': 'Dhumatti Haaromfame',
        'status': 'Haala',
        'at': 'irratti',
      },
    };

    return AppLocalizations(locale, localizedValues);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

// Extension method for easy access to translations
extension LocalizationExtension on BuildContext {
  String translate(String key) {
    return AppLocalizations.of(this)?.translate(key) ?? key;
  }
}
